name: release
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: "Version Name"
        required: true
jobs:
  Release:
    name: Build and Release the library
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew :okdynamic:build
      - name: Publish the library
        run: |
          ./gradlew publish
        env:
          username_github: ${{ secrets.username_github }}
          key_github: ${{ secrets.key_github }}
      - name: Create new tag
        run: |
          git config --global user.email "j_mly@ymail.com"
          git config --global user.name "jimlyas"
          git tag -a $TAG -m "Release v$TAG"
          git push origin $TAG
        env:
          TAG: ${{ github.event.inputs.versionName }}
      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.event.inputs.versionName }}
          tag: ${{ github.event.inputs.versionName }}
          artifacts: "okdynamic/build/outputs/aar/okdynamic-debug.aar"
          bodyFile: "README.md"
          token: ${{ secrets.KEY_GITHUB }}